### ISSUE TITLE
How to change CSS?

### ISSUE THREAD

**Issue by bblarsen-sci** [dms-vep/dms-vep.github.io#11]
@WillHannon-MCB I don't quite understand how CSS formatting works for these pages. 

I am trying to change some formatting on my markdown pages with some custom CSS.  I guess I'm a little confused about how CSS stylings work in general for the website. Is there a global file that we can edit for each VEP specifically if we want to customize formatting without applying it to all the other pages? Right now I am manually adding CSS in the markdown file to make my caption font smaller and in grey (because I think it looks better).  Or is it only possible to do manually for each figure caption as I do here:

`<figcaption style="color: gray; font-size: 0.8em; text-align: center;">`

<img width="811" alt="Screenshot 2024-02-16 at 2 19 49 PM" src="https://github.com/dms-vep/dms-vep.github.io/assets/89543163/089a178c-c5bf-416c-bb05-ae0e08d75569">

Either way, it would be useful to have something in the readme instructions on how to do different types of formatting.

**Comment by WillHannon-MCB** [comment]
I'd prefer not to mess with the styling for individual VEP pages. Going to different pages of the same site and having totally differently styling is not a good look.

However, if you have a strong opinion about the CSS style of elements on a site we can change them globally. Generally, consistency is good with things like this.
